# Generated by Django 2.2 on 2019-11-19 06:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('gender', multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Female'), ('M', 'Male')], max_length=3)),
                ('sports', multiselectfield.db.fields.MultiSelectField(choices=[('Kaba', 'Kabaddi'), ('Crick', 'Cricket'), ('Volly', 'Vollyball'), ('Soccer', 'Soccer'), ('Basket', 'Basketball'), ('Base', 'Baseball'), ('Minton', 'Badminton'), ('Carrom', 'Carrom'), ('Swim', 'Swimming'), ('Chess', 'Chess'), ('Gym', 'Gymnastics')], max_length=25)),
                ('data_of_joining', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SportsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(max_length=50)),
                ('sports_type', models.CharField(max_length=50)),
                ('sports_time', models.DateField(max_length=35)),
                ('sports_coach', models.CharField(max_length=70)),
            ],
        ),
    ]
